#!/usr/bin/env python3
#
# /Users/fahadnabid/Documents/default/MFC/tests/52A7542F/case.py:
# 1D -> Example -> jwl_cj_products

import json
import argparse

parser = argparse.ArgumentParser(
    prog="/Users/fahadnabid/Documents/default/MFC/tests/52A7542F/case.py",
    description="/Users/fahadnabid/Documents/default/MFC/tests/52A7542F/case.py: 1D -> Example -> jwl_cj_products",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)

parser.add_argument("--mfc", type=json.loads, default='{}', metavar="DICT",
                    help="MFC's toolchain's internal state.")

ARGS = vars(parser.parse_args())

case = {
    "run_time_info": "T",
    "m": 399,
    "n": 0,
    "p": 0,
    "dt": 1e-12,
    "t_step_start": 0,
    "t_step_stop": 8,
    "t_step_save": 8,
    "num_patches": 2,
    "model_eqns": 2,
    "alt_soundspeed": "F",
    "num_fluids": 2,
    "mpp_lim": "T",
    "mixture_err": "T",
    "time_stepper": 3,
    "recon_type": 2,
    "mapped_weno": "F",
    "null_weights": "F",
    "mp_weno": "F",
    "riemann_solver": 1,
    "wave_speeds": 1,
    "avg_state": 2,
    "format": 1,
    "precision": 2,
    "patch_icpp(1)%pres": 101325.0,
    "patch_icpp(1)%alpha_rho(1)": 1.63e-05,
    "patch_icpp(1)%alpha(1)": 1e-08,
    "patch_icpp(2)%pres": 34490901325.0,
    "patch_icpp(2)%alpha_rho(1)": 2933.9999706599997,
    "patch_icpp(2)%alpha(1)": 0.99999999,
    "patch_icpp(3)%pres": 0.1,
    "patch_icpp(3)%alpha_rho(1)": 0.125,
    "patch_icpp(3)%alpha(1)": 1.0,
    "fluid_pp(1)%gamma": 2.5,
    "fluid_pp(1)%pi_inf": 0.0,
    "fluid_pp(1)%cv": 613.5,
    "fluid_pp(1)%qv": 0.0,
    "fluid_pp(1)%qvp": 0.0,
    "bubbles_euler": "F",
    "pref": 101325.0,
    "rhoref": 1000.0,
    "bubble_model": 3,
    "polytropic": "T",
    "polydisperse": "F",
    "thermal": 3,
    "patch_icpp(1)%r0": 1,
    "patch_icpp(1)%v0": 0,
    "patch_icpp(2)%r0": 1,
    "patch_icpp(2)%v0": 0,
    "patch_icpp(3)%r0": 1,
    "patch_icpp(3)%v0": 0,
    "qbmm": "F",
    "dist_type": 2,
    "poly_sigma": 0.3,
    "sigR": 0.1,
    "sigV": 0.1,
    "rhoRV": 0.0,
    "acoustic_source": "F",
    "num_source": 1,
    "acoustic(1)%loc(1)": 0.5,
    "acoustic(1)%mag": 0.2,
    "acoustic(1)%length": 0.25,
    "acoustic(1)%dir": 1.0,
    "acoustic(1)%npulse": 1,
    "acoustic(1)%pulse": 1,
    "rdma_mpi": "F",
    "bubbles_lagrange": "F",
    "lag_params%nBubs_glb": 1,
    "lag_params%solver_approach": 0,
    "lag_params%cluster_type": 2,
    "lag_params%pressure_corrector": "F",
    "lag_params%smooth_type": 1,
    "lag_params%epsilonb": 1.0,
    "lag_params%heatTransfer_model": "F",
    "lag_params%massTransfer_model": "F",
    "lag_params%valmaxvoid": 0.9,
    "x_domain%beg": 0.0,
    "x_domain%end": 1.0,
    "n_start": 0,
    "jwl_mix_type": 0,
    "muscl_order": 2,
    "muscl_lim": 2,
    "bc_x%beg": -1,
    "bc_x%end": -1,
    "prim_vars_wrt": "T",
    "cons_vars_wrt": "F",
    "rho_wrt": "T",
    "pres_wrt": "T",
    "E_wrt": "T",
    "c_wrt": "T",
    "parallel_io": "F",
    "patch_icpp(1)%geometry": 1,
    "patch_icpp(1)%x_centroid": 0.5,
    "patch_icpp(1)%length_x": 1.0,
    "patch_icpp(1)%vel(1)": 0.0,
    "patch_icpp(1)%alpha_rho(2)": 1.22499998775,
    "patch_icpp(1)%alpha(2)": 0.99999999,
    "patch_icpp(2)%geometry": 1,
    "patch_icpp(2)%alter_patch(1)": "T",
    "patch_icpp(2)%x_centroid": 0.1,
    "patch_icpp(2)%length_x": 0.2,
    "patch_icpp(2)%vel(1)": 3066.6666666666665,
    "patch_icpp(2)%alpha_rho(2)": 1.225e-08,
    "patch_icpp(2)%alpha(2)": 1e-08,
    "fluid_pp(1)%eos": 2,
    "fluid_pp(1)%jwl_A": 371200000000.0,
    "fluid_pp(1)%jwl_B": 3231000000.0,
    "fluid_pp(1)%jwl_R1": 4.15,
    "fluid_pp(1)%jwl_R2": 0.95,
    "fluid_pp(1)%jwl_omega": 0.3,
    "fluid_pp(1)%jwl_rho0": 1630.0,
    "fluid_pp(1)%jwl_E0": 10089000000.0,
    "fluid_pp(1)%jwl_air_e0": 255750.0,
    "fluid_pp(1)%jwl_air_rho0": 1.225,
    "fluid_pp(1)%jwl_air_gamma": 0.4,
    "fluid_pp(2)%eos": 1,
    "fluid_pp(2)%gamma": 2.5,
    "fluid_pp(2)%pi_inf": 0.0,
    "fluid_pp(2)%cv": 717.5
}
mods = {}

if "post_process" in ARGS["mfc"]["targets"]:
    mods = {"parallel_io": "T", "cons_vars_wrt": "T", "prim_vars_wrt": "T", "alpha_rho_wrt(1)": "T", "rho_wrt": "T", "mom_wrt(1)": "T", "vel_wrt(1)": "T", "E_wrt": "T", "pres_wrt": "T", "alpha_wrt(1)": "T", "gamma_wrt": "T", "heat_ratio_wrt": "T", "pi_inf_wrt": "T", "pres_inf_wrt": "T", "c_wrt": "T"}
    if case['p'] != 0:
        mods.update({"fd_order": 1, "omega_wrt(1)": "T", "omega_wrt(2)": "T", "omega_wrt(3)": "T"})
else:
    mods = {"parallel_io": "F", "prim_vars_wrt": "F"}

print(json.dumps({**case, **mods}))
