#!/usr/bin/env python3
"""Minimal eight-rank particle-bed + AMR baseline.

Four fixed circles are generated through particle_cloud, not patch_ib, so this
exercises cloud placement, MPI neighborhood reduction, IBM, and a static AMR
block together.  A small Mach-1.5 shock reaches the bed during this 120-step
run.  The 32x32 coarse AMR block becomes 63x63 fine cells and fits an 8-rank
local split of the 256x256 base grid.
"""

import json

case = {
    "run_time_info": "T",
    "format": "silo",
    "precision": "double",
    "parallel_io": "F",
    "prim_vars_wrt": "T",
    "rho_wrt": "T",
    "pres_wrt": "T",
    "vel_wrt(1)": "T",
    "vel_wrt(2)": "T",
    "ib_state_wrt": "T",
    "x_domain%beg": 0.0,
    "x_domain%end": 1.0,
    "y_domain%beg": 0.0,
    "y_domain%end": 1.0,
    "m": 255,
    "n": 255,
    "p": 0,
    "dt": 5.0e-4,
    "t_step_start": 0,
    "t_step_stop": 120,
    "t_step_save": 40,
    "num_patches": 2,
    "model_eqns": "5eq",
    "num_fluids": 1,
    "mpp_lim": "F",
    "mixture_err": "T",
    "time_stepper": "rk3",
    "weno_order": 5,
    "weno_eps": 1.0e-16,
    "weno_Re_flux": "T",
    "weno_avg": "T",
    "avg_state": "arithmetic",
    "mapped_weno": "T",
    "null_weights": "F",
    "mp_weno": "T",
    "riemann_solver": "hllc",
    "wave_speeds": "direct",
    "viscous": "T",
    "fd_order": 2,
    "bc_x%beg": -17,
    "bc_x%end": -3,
    "bc_y%beg": -1,
    "bc_y%end": -1,
    "patch_icpp(1)%geometry": 3,
    "patch_icpp(1)%x_centroid": 0.5,
    "patch_icpp(1)%y_centroid": 0.5,
    "patch_icpp(1)%length_x": 1.0,
    "patch_icpp(1)%length_y": 1.0,
    "patch_icpp(1)%vel(1)": 0.0,
    "patch_icpp(1)%vel(2)": 0.0,
    "patch_icpp(1)%pres": 1.0,
    "patch_icpp(1)%alpha_rho(1)": 1.4,
    "patch_icpp(1)%alpha(1)": 1.0,
    "patch_icpp(2)%geometry": 3,
    "patch_icpp(2)%x_centroid": 0.19,
    "patch_icpp(2)%y_centroid": 0.5,
    "patch_icpp(2)%length_x": 0.38,
    "patch_icpp(2)%length_y": 1.0,
    "patch_icpp(2)%alter_patch(1)": "T",
    "patch_icpp(2)%vel(1)": 0.6944,
    "patch_icpp(2)%vel(2)": 0.0,
    "patch_icpp(2)%pres": 2.4583,
    "patch_icpp(2)%alpha_rho(1)": 2.6069,
    "patch_icpp(2)%alpha(1)": 1.0,
    "fluid_pp(1)%gamma": 2.5,
    "fluid_pp(1)%pi_inf": 0.0,
    "fluid_pp(1)%Re(1)": 2.5e5,
    # Static particle bed: particles are generated at startup, then stay fixed.
    "ib": "T",
    "num_ibs": 0,
    "num_particle_clouds": 1,
    "many_ib_patch_parallelism": "T",
    "particle_cloud(1)%x_centroid": 0.5,
    "particle_cloud(1)%y_centroid": 0.5,
    "particle_cloud(1)%z_centroid": 0.0,
    "particle_cloud(1)%length_x": 0.09,
    "particle_cloud(1)%length_y": 0.09,
    "particle_cloud(1)%length_z": 0.0,
    "particle_cloud(1)%num_particles": 4,
    "particle_cloud(1)%radius": 0.015,
    "particle_cloud(1)%mass": 0.01,
    "particle_cloud(1)%min_spacing": 0.002,
    "particle_cloud(1)%moving_ibm": 0,
    "particle_cloud(1)%seed": 8173,
    "particle_cloud(1)%cloud_geometry": 1,
    "particle_cloud(1)%packing_method": 1,
    "particle_cloud(1)%periodic": 0,
    "amr": "T",
    "amr_ref_ratio": 2,
    "amr_max_level": 1,
    "amr_max_blocks": 1,
    "amr_max_grid_size": 32,
    "amr_subcycle": "T",
    "amr_block_beg(1)": 112,
    "amr_block_end(1)": 143,
    "amr_block_beg(2)": 112,
    "amr_block_end(2)": 143,
    "amr_regrid_int": 0,
}

print(json.dumps(case, indent=4))
