#!/usr/bin/env python3
"""Deterministic eight-rank CPU IBM + one-block-AMR smoke case.

The case has its own directory so its eight-rank AMR restart data cannot be
mixed with the one-rank local-smoke output.

Run:
    ./mfc.sh run examples/2D_ibm_amr_8cpu_smoke/case.py --no-gpu -n 8
"""

import json

case = {
    "run_time_info": "T",
    "format": "silo",
    "precision": "double",
    "parallel_io": "T",
    "prim_vars_wrt": "T",
    "rho_wrt": "T",
    "pres_wrt": "T",
    "vel_wrt(1)": "T",
    "vel_wrt(2)": "T",
    "x_domain%beg": 0.0,
    "x_domain%end": 1.0,
    "y_domain%beg": 0.0,
    "y_domain%end": 1.0,
    "m": 255,
    "n": 255,
    "p": 0,
    "dt": 1.0e-4,
    "t_step_start": 0,
    "t_step_stop": 20,
    "t_step_save": 20,
    "num_patches": 1,
    "model_eqns": "5eq",
    "num_fluids": 1,
    "mpp_lim": "F",
    "mixture_err": "T",
    "time_stepper": "rk3",
    "weno_order": 5,
    "weno_eps": 1.0e-16,
    "mapped_weno": "T",
    "mp_weno": "T",
    "riemann_solver": "hllc",
    "wave_speeds": "direct",
    "avg_state": "arithmetic",
    "bc_x%beg": -3,
    "bc_x%end": -3,
    "bc_y%beg": -3,
    "bc_y%end": -3,
    "patch_icpp(1)%geometry": 3,
    "patch_icpp(1)%x_centroid": 0.5,
    "patch_icpp(1)%y_centroid": 0.5,
    "patch_icpp(1)%length_x": 1.0,
    "patch_icpp(1)%length_y": 1.0,
    "patch_icpp(1)%vel(1)": 0.0,
    "patch_icpp(1)%vel(2)": 0.0,
    "patch_icpp(1)%pres": 1.0,
    "patch_icpp(1)%alpha_rho(1)": 1.0,
    "patch_icpp(1)%alpha(1)": 1.0,
    "fluid_pp(1)%gamma": 2.5,
    "fluid_pp(1)%pi_inf": 0.0,
    "ib": "T",
    "num_ibs": 1,
    "fd_order": 2,
    "viscous": "F",
    "patch_ib(1)%geometry": 2,
    "patch_ib(1)%x_centroid": 0.488,
    "patch_ib(1)%y_centroid": 0.513,
    "patch_ib(1)%radius": 0.04,
    "patch_ib(1)%slip": "F",
    "amr": "T",
    "amr_ref_ratio": 2,
    "amr_max_level": 1,
    "amr_max_blocks": 1,
    "amr_max_grid_size": 24,
    "amr_subcycle": "T",
    "amr_block_beg(1)": 116,
    "amr_block_end(1)": 139,
    "amr_block_beg(2)": 116,
    "amr_block_end(2)": 139,
    "amr_regrid_int": 0,
}

print(json.dumps(case, indent=4))
