#!/usr/bin/env python3
"""Eight-rank mixed-resolution IBM case.

Four equal fixed circles are exposed to a Mach-1.5 shock.  Bodies 1 and 2 lie
completely within the static AMR block and are resolved on its 2:1 fine grid;
bodies 3 and 4 lie outside it and remain on the coarse grid.  This directly
tests simultaneous fine- and coarse-grid IBM correction.
"""

import json

case = {
    "run_time_info": "T",
    "format": "silo",
    "precision": "double",
    "parallel_io": "F",
    "prim_vars_wrt": "T",
    "rho_wrt": "T",
    "pres_wrt": "T",
    "vel_wrt(1)": "T",
    "vel_wrt(2)": "T",
    "ib_state_wrt": "T",
    "x_domain%beg": 0.0,
    "x_domain%end": 1.0,
    "y_domain%beg": 0.0,
    "y_domain%end": 1.0,
    "m": 255,
    "n": 255,
    "p": 0,
    "dt": 5.0e-4,
    "t_step_start": 0,
    "t_step_stop": 120,
    "t_step_save": 40,
    "num_patches": 2,
    "model_eqns": "5eq",
    "num_fluids": 1,
    "mpp_lim": "F",
    "mixture_err": "T",
    "time_stepper": "rk3",
    "weno_order": 5,
    "weno_eps": 1.0e-16,
    "weno_Re_flux": "T",
    "weno_avg": "T",
    "avg_state": "arithmetic",
    "mapped_weno": "T",
    "null_weights": "F",
    "mp_weno": "T",
    "riemann_solver": "hllc",
    "wave_speeds": "direct",
    "viscous": "T",
    "fd_order": 2,
    "bc_x%beg": -17,
    "bc_x%end": -3,
    "bc_y%beg": -1,
    "bc_y%end": -1,
    "patch_icpp(1)%geometry": 3,
    "patch_icpp(1)%x_centroid": 0.5,
    "patch_icpp(1)%y_centroid": 0.5,
    "patch_icpp(1)%length_x": 1.0,
    "patch_icpp(1)%length_y": 1.0,
    "patch_icpp(1)%vel(1)": 0.0,
    "patch_icpp(1)%vel(2)": 0.0,
    "patch_icpp(1)%pres": 1.0,
    "patch_icpp(1)%alpha_rho(1)": 1.4,
    "patch_icpp(1)%alpha(1)": 1.0,
    "patch_icpp(2)%geometry": 3,
    "patch_icpp(2)%x_centroid": 0.20,
    "patch_icpp(2)%y_centroid": 0.5,
    "patch_icpp(2)%length_x": 0.40,
    "patch_icpp(2)%length_y": 1.0,
    "patch_icpp(2)%alter_patch(1)": "T",
    "patch_icpp(2)%vel(1)": 0.6944,
    "patch_icpp(2)%vel(2)": 0.0,
    "patch_icpp(2)%pres": 2.4583,
    "patch_icpp(2)%alpha_rho(1)": 2.6069,
    "patch_icpp(2)%alpha(1)": 1.0,
    "fluid_pp(1)%gamma": 2.5,
    "fluid_pp(1)%pi_inf": 0.0,
    "fluid_pp(1)%Re(1)": 2.5e5,
    "ib": "T",
    "num_ibs": 4,
    "many_ib_patch_parallelism": "T",
    # Fine-grid bodies: AMR region is x,y in [0.4375, 0.5625].
    "patch_ib(1)%geometry": 2,
    "patch_ib(1)%x_centroid": 0.475,
    "patch_ib(1)%y_centroid": 0.475,
    "patch_ib(1)%radius": 0.015,
    "patch_ib(1)%slip": "F",
    "patch_ib(2)%geometry": 2,
    "patch_ib(2)%x_centroid": 0.525,
    "patch_ib(2)%y_centroid": 0.525,
    "patch_ib(2)%radius": 0.015,
    "patch_ib(2)%slip": "F",
    # Coarse-grid bodies, deliberately outside the AMR footprint.
    "patch_ib(3)%geometry": 2,
    "patch_ib(3)%x_centroid": 0.350,
    "patch_ib(3)%y_centroid": 0.475,
    "patch_ib(3)%radius": 0.015,
    "patch_ib(3)%slip": "F",
    "patch_ib(4)%geometry": 2,
    "patch_ib(4)%x_centroid": 0.650,
    "patch_ib(4)%y_centroid": 0.525,
    "patch_ib(4)%radius": 0.015,
    "patch_ib(4)%slip": "F",
    "amr": "T",
    "amr_ref_ratio": 2,
    "amr_max_level": 1,
    "amr_max_blocks": 1,
    "amr_max_grid_size": 32,
    "amr_subcycle": "T",
    "amr_block_beg(1)": 112,
    "amr_block_end(1)": 143,
    "amr_block_beg(2)": 112,
    "amr_block_end(2)": 143,
    "amr_regrid_int": 0,
}

print(json.dumps(case, indent=4))
